version: 2.1
orbs:
  python: circleci/python@3.0.0
jobs:
  build_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests using Pytest
          command: pytest -vvv

workflows:
  build-test:
    jobs:
      - build_test
