version: 2.1
orbs:
  python: circleci/python@3.0.0
  aws-cli: circleci/aws-cli@5.1.2
  aws-s3: circleci/aws-s3@4.1.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: python/default
    steps:
      - run:
          name: Run tests using Pytest
          command: python -m pytest
      - store_test_results:
          path: test-results
workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
