version: 2.1
orbs:
  aws-s3: circleci/aws-s3@4.1.0
  aws-cli: circleci/aws-cli@5.1
jobs:
  aws-cli-install:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
        profile_name: aws-s3-superuser
      - run: aws s3 ls

workflows:
  deploy_to_aws_s3:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
