version: 2.1
orbs:
  aws-s3: circleci/aws-s3@4.1.0
  aws-cli: circleci/aws-cli@5.1
jobs:
  aws-cli-install:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
        profile_name: aws-s3-superuser
        aws_access_key_id: $AWS_ACCESS_KEY_ID
        aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
        aws_region: $AWS_REGION
      - run: aws s3 sync . s3://aws-web-scraper

workflows:
  deploy_to_aws_s3:
    jobs:
      - aws-cli-install:
          filters:
            branches:
              only:
                - main
