version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
jobs:
  build-deploy:
    executor: aws-cli/default
    steps:
      - run: aws s3 sync . s3://web-scraper

workflows:
  deploy_to_aws_s3:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - main
